version: '3.3'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - '3001:3000'