version: '3'

services:
    gadgethorse:
        build: src
        restart: unless-stopped
        environment:
            DATABASE_HOST: gadgethorse-database
            DATABASE_DB: gadgethorse
            DATABASE_USER: MOlUnUDpyuRFABtucSyX
            DATABASE_PASSWORD: WcYLQqEUsedRqgsrZyEL4kmd
        ports:
            - 3000:3000
        depends_on:
            - gadgethorse-database
        volumes:
            - ./data:/data

    gadgethorse-database:
        image: mariadb
        restart: unless-stopped
        environment:
            MARIADB_USER: MOlUnUDpyuRFABtucSyX
            MARIADB_PASSWORD: WcYLQqEUsedRqgsrZyEL4kmd
            MARIADB_DATABASE: gadgethorse
            MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
