services:
    web:
        build: .
        ports:
            - 9000:80
        environment:
            HEADLESS_AUTH: supersecret
            HEADLESS_HOST: headless:5000
            ADMIN_TOKEN: supersecret
            CHALLENGE_URL: http://web
            CHECKER_TOKEN: supersecret
            FLAG: CCIT{REDACTED}

    headless:
        image: cybersecnatlab/challenge-headless:latest-manager
        restart: unless-stopped
        environment:
            AUTH_TOKEN: supersecret
            RABBITMQ_HOST: headless-rabbitmq
            RABBITMQ_QUEUE: headless-jobs
        depends_on:
            - headless-rabbitmq

    headless-rabbitmq:
        image: rabbitmq:3.11
        restart: unless-stopped

    headless-worker:
        image: cybersecnatlab/challenge-headless:latest-worker
        restart: unless-stopped
        environment:
            RABBITMQ_HOST: headless-rabbitmq
            RABBITMQ_QUEUE: headless-jobs
        deploy:
            replicas: 1
        depends_on:
            - headless-rabbitmq
